apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  index.html: <h1>Welcome to the Vault</h1><p>Configured by Kubernetes.</p>

---

apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
type: Opaque
data:
  passcode: c3VwZXJzZWNyZXQ=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault-container
          image: nginx:alpine
          env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: vault-secret
                key: passcode
          volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: vault-config

---

apiVersion: v1
kind: Service
metadata:
  name: vault-svc
spec:
  type: NodePort
  selector:
    app: vault
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009